version: '3.7'

services:
  web-server:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
  
  database:
    image: mysql:latest
    volumes:
      - type: volume
        source: mysql-db
        target: /app
    restart: always
  
  web-app:
    build: .
    depends_on:
      - "database"
      - "web-server"
    ports:
      - "5000"
    restart: always

volumes:
  mysql-db:
