version: '3.7'

services:
  ghost-platform:
    image: ghost:1-alpine
    depends_on:
      - data-base
    ports:
      - "6000:6000"

  data-base:
    image: mysql:latest
    volumes:
      - type: volume
        source: mysql-db
        target: /app
    restart: always

volumes:
  mysql-db: